### PR TITLE
Add Flex support. Clean Makefile. Clean NBGL main menu code.

### PR DESCRIPTION
**Pull request by agrojean-ledger**
# Checklist

- [x] Target branch is `develop` 
- [x] Application version has been bumped

### CODE REVIEW

**Review by cedelavergne-ledger — COMMENTED** [review]
No specific comments.
Just fix please the :red_circle: workflows

**Review by tdejoigny-ledger — COMMENTED** [review]
Are there no other flows to go through for the new Nbgl flows (in `nbgl_ui.c`) ? 
Especially to avoid having hardcoded strings in the app's code.

**Comment by agrojean-ledger** [comment]
@cedelavergne-ledger the CI jobs that fail are related to static analysis, specifically `no_throw` cx functions of which return value is ignored.

The problem is that the whole app's architecture is based on `THROW` and does not propagate errors through returned codes... Hard to refactor it.

**Comment by agrojean-ledger** [comment]
@tdejoigny-ledger I tried using `nbgl_useCaseReview` to avoid having all these hard coded strings but the app's architecture requires `nbgl_useCaseReviewStart` :

1. Display review start
2. Display tag value list (amount, destination)
3. Call `continueCallback` when main panel is touched : compute transaction fees (the app does not compute fees before the start of the review...),
4. Display transaction fees.

There's one case where `nbgl_useCaseReview` could be used : for message signing, but using it only for this type of transaction makes the code weird and harder to read (because this API has to coexist with `nbgl_useCaseReviewStart`)...

**Comment by tdejoigny-ledger** [comment]
> @cedelavergne-ledger the CI jobs that fail are related to static analysis, specifically `no_throw` cx functions of which return value is ignored.
> 
> The problem is that the whole app's architecture is based on `THROW` and does not propagate errors through returned codes... Hard to refactor it.

Is there only one warning to fix ?  if it's the case we could do the job especially by using assert

**Comment by agrojean-ledger** [comment]
> > @cedelavergne-ledger the CI jobs that fail are related to static analysis, specifically `no_throw` cx functions of which return value is ignored.
> > The problem is that the whole app's architecture is based on `THROW` and does not propagate errors through returned codes... Hard to refactor it.
> 
> Is there only one warning to fix ? if it's the case we could do the job especially by using assert

@cedelavergne-ledger  There are many `no_throw` calls in the code that generate warnings.

**Pull request merged**
